apiVersion: apps/v1
kind: Deployment
metadata:
  name: nf-deployment
  labels:
    app: nf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nf
  template:
    metadata:
      labels:
        app: nf
    spec:
      containers:
        - name: nf
          image: x00169650/newsfetcher:v1
